export const UNEXPECTED_ERROR = 'An unexpected error occurred'
export const TASK_CREATED = 'A task was successfully created'
export const TASK_DELETED = 'A task was successfully deleted'
export const TASK_UPDATE = 'A task was updated successfully'
export const TASK_POSITIONS_UPDATE = 'Tasks updated successfully!'
export const COPY = 'Copy and save it somewhere'
